// Generate src/components/ui/icon.tsx — a lucide-compatible barrel backed by
// Line Awesome (Icons8) SVGs. Run after changing the map below:
//   node scripts/build-icons.mjs
import { readFile, writeFile, access } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(fileURLToPath(import.meta.url), "../..");
const svgDir = path.join(root, "node_modules/line-awesome/svg");

// lucide export name → Line Awesome svg basename (all "-solid").
const MAP = {
  AlertCircle: "exclamation-circle-solid",
  ArrowLeft: "arrow-left-solid",
  ArrowRight: "arrow-right-solid",
  Bell: "bell-solid",
  BellRing: "bell-solid",
  Bold: "bold-solid",
  Boxes: "boxes-solid",
  Check: "check-solid",
  CheckCircle2: "check-circle-solid",
  CheckIcon: "check-solid",
  ChevronDown: "angle-down-solid",
  ChevronDownIcon: "angle-down-solid",
  ChevronLeft: "angle-left-solid",
  ChevronRight: "angle-right-solid",
  ChevronRightIcon: "angle-right-solid",
  ChevronUp: "angle-up-solid",
  ChevronUpIcon: "angle-up-solid",
  CircleCheckIcon: "check-circle-solid",
  CircleUser: "user-circle-solid",
  Copy: "copy-solid",
  Database: "database-solid",
  Download: "download-solid",
  ExternalLink: "external-link-alt-solid",
  Eye: "eye-solid",
  EyeOff: "eye-slash-solid",
  FileText: "file-alt-solid",
  Gift: "gift-solid",
  Heading2: "heading-solid",
  Heart: "heart-solid",
  Home: "home-solid",
  Image: "image-solid",
  ImageIcon: "image-solid",
  Images: "images-solid",
  Inbox: "inbox-solid",
  Info: "info-circle-solid",
  InfoIcon: "info-circle-solid",
  Italic: "italic-solid",
  LayoutDashboard: "th-large-solid",
  Link: "link-solid",
  LinkIcon: "link-solid",
  List: "list-ul-solid",
  ListOrdered: "list-ol-solid",
  Loader2: "circle-notch-solid",
  Loader2Icon: "circle-notch-solid",
  Lock: "lock-solid",
  LogOut: "sign-out-alt-solid",
  Mail: "envelope-solid",
  MailOpen: "envelope-open-solid",
  MapPin: "map-marker-alt-solid",
  Megaphone: "bullhorn-solid",
  Menu: "bars-solid",
  MessageCircle: "comment-solid",
  Minus: "minus-solid",
  MoreVertical: "ellipsis-v-solid",
  Newspaper: "newspaper-solid",
  OctagonXIcon: "times-circle-solid",
  Package: "box-solid",
  PanelLeft: "columns-solid",
  PanelLeftClose: "columns-solid",
  Pencil: "pen-solid",
  Phone: "phone-solid",
  Plus: "plus-solid",
  Quote: "quote-left-solid",
  Redo2: "redo-alt-solid",
  RefreshCw: "sync-alt-solid",
  ScrollText: "scroll-solid",
  Search: "search-solid",
  Settings: "cog-solid",
  Shield: "shield-alt-solid",
  ShieldAlert: "shield-alt-solid",
  ShieldCheck: "shield-alt-solid",
  ShoppingBag: "shopping-bag-solid",
  ShoppingCart: "shopping-cart-solid",
  SlidersHorizontal: "sliders-h-solid",
  Sparkles: "magic-solid",
  Star: "star-solid",
  Tags: "tags-solid",
  Trash2: "trash-alt-solid",
  TriangleAlertIcon: "exclamation-triangle-solid",
  Truck: "truck-solid",
  Undo2: "undo-alt-solid",
  Upload: "upload-solid",
  User: "user-solid",
  UserCog: "user-cog-solid",
  UserPlus: "user-plus-solid",
  Users: "users-solid",
  X: "times-solid",
  XCircle: "times-circle-solid",
  XIcon: "times-solid",
  ZoomIn: "search-plus-solid",
};

const exists = (f) =>
  access(path.join(svgDir, f)).then(
    () => true,
    () => false,
  );

/** pull viewBox + inner markup out of a Line Awesome svg file */
async function glyph(base) {
  for (const cand of [`${base}.svg`, `${base.replace(/-solid$/, "")}.svg`]) {
    if (await exists(cand)) {
      const raw = await readFile(path.join(svgDir, cand), "utf8");
      const vb = (raw.match(/viewBox="([^"]+)"/) || [])[1] || "0 0 32 32";
      const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
      return { vb, inner, file: cand };
    }
  }
  return null;
}

const missing = [];
const parts = [];
for (const [name, base] of Object.entries(MAP)) {
  const g = await glyph(base);
  if (!g) {
    missing.push(`${name} -> ${base}`);
    continue;
  }
  parts.push(
    `export const ${name}: Icon = (p) => (\n` +
      `  <svg viewBox="${g.vb}" fill="currentColor" aria-hidden {...p} className={cx(p.className)}>${g.inner}</svg>\n` +
      `);`,
  );
}

const file =
  `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.\n` +
  `// Line Awesome icons (© Icons8, SIL OFL 1.1 / MIT). Names mirror lucide-react\n` +
  `// so call-sites only change the import path.\n` +
  `import type { SVGProps, FC } from "react";\n\n` +
  `export type IconProps = SVGProps<SVGSVGElement>;\n` +
  `export type Icon = FC<IconProps>;\n` +
  `/** kept for code that typed props as \`LucideIcon\` */\n` +
  `export type LucideIcon = Icon;\n\n` +
  `const cx = (c?: string) => ["inline-block shrink-0", c].filter(Boolean).join(" ");\n\n` +
  parts.join("\n\n") +
  "\n";

await writeFile(path.join(root, "src/components/ui/icon.tsx"), file);
console.log(`wrote src/components/ui/icon.tsx — ${parts.length} icons`);
if (missing.length) {
  console.log("\nMISSING (fix the map):");
  for (const m of missing) console.log("  " + m);
  process.exit(1);
}
